# Transform the DESCRIPTION file in its tidy version
on:
  push:
    paths: ["DESCRIPTION"]

name: tidy-DESCRIPTION

jobs:
  tidy-DESCRIPTION:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::usethis
          needs: usethis

      - name: Make DESCRIPTION tidy
        run: usethis::use_tidy_description()
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add DESCRIPTION
          git commit -m "Update DESCRIPTION" || echo "No changes to commit"
          git pull --ff-only
          git push origin
